# Navigation Links

main:
  - name: About
    url: /#about
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Career
    url: /#career
    weight: 30
  - name: Projects
    url: /#projects
    weight: 40
  - name: Services
    url: /#services
    weight: 50
  - name: Awards
    url: /#awards
    weight: 60
  - name: Papers
    url: /papers/
    weight: 70
  - name: Media
    url: /#media
    weight: 80
  - name: Contact
    url: /#contact
    weight: 90
  - name: CV
    url: uploads/resume.pdf
    weight: 100
